arr = list(map(int, input("Enter numbers separated by space: ").split()))
x= max(arr)
arr.remove(x)
y= max(arr)
print("2nd largest number is:", y)
a= min(arr)
arr.remove(a)   
b= min(arr)
print("2nd smallest number is:", b)